### ISSUE TITLE
basic marker properties (stroke color, width, marker_z) are absent for graph nodes

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GraphRecipes.jl#108]
MWE:
```julia
using GraphRecipes, Plots
using LightGraphs
N=8
g = barabasi_albert(N, 1; seed = 42)
weights = [length(neighbors(g, i)) for i in 1:nv(g)]
p = graphplot(g, curves=false, node_weights = weights, color = "black",
nodeshape = :circle, marker_z = rand(N))
```
@mkborregaard  instructed me that the above would create a nice plot of the graph, where the node colors would be the `rand(N)` (mapped to a colormap), and to the right-hand side of the plot there would be a colorbar. I'd very much would like to be able to do that, because I am defining a plot recipe for Agents.jl. 

At the moment the argument `marker_z` seem to have no effect.

**Comment by mkborregaard** [comment]
I bet this is due to the reimplementation of nodes as shapes rather than markers. Setting `fill_z := plotattributes[:marker_z]` on the series of the markers inside the recipe might be enough to fix.

**Comment by Datseris** [comment]
if you have a branch where this is done I can test it for you.

**Comment by JackDevine** [comment]
The attribute that you are looking for is `nodecolor`, which only has one alias:
```julia
julia> GraphRecipes.graph_aliases[:nodecolor]
1-element Array{Symbol,1}:
 :marker_color
```
So adding `marker_z` to the aliases would get you halfway to a fix. The other problem is that `nodecolor` only accepts colors. To get your example to work, you need to do:
```julia
nodecolor_range = range(colorant"yellow", stop=colorant"red", length=N)

p = graphplot(g, curves=false, node_weights = weights, color = "black",
nodeshape = :circle, nodecolor = [nodecolor_range[rand(1:N)] for _ in 1:N])
```

**Comment by mkborregaard** [comment]
That's not really an ideomatic design. The fact that nodes aren't markers should be hidden to the user - any Plots user would expect `marker_z` to JustWork.

**Comment by JackDevine** [comment]
Ok, I can see now that `marker_z` is different from `markercolor`, so they shouldn't be aliases.

Looking at:
http://docs.juliaplots.org/latest/generated/attributes_series/
I can see that there are quite a few marker properties that need to be implemented for nodes. That leaves us with two options:
1. Reimplement all of the marker related functionality for nodes.
2. Come up with a way to find the perimeter of a marker from within `graphplot`

**Comment by Datseris** [comment]
@JackDevine using `nodecolor_range = range(colorant"yellow", stop=colorant"red", length=N)` is not really an option. I want to be able to use _real numbers_ as with any colorbar, and make the nodes of my graph have the color of the real number mapped to an arbitrary color map. 

I found this very hard to do so far, and besides, it is very important to have a colorbar to the right side of my plot, so that the color can be translated into a value. (In fact I found this impossible to do so far, maybe there is a way, but I haven't found it)

**Comment by JackDevine** [comment]
It is not possible to have color bars with GraphRecipes, although I agree that it would be useful.

I think that the Colors package does allow you to interpolate between two colors, which would solve your problem, modulo the colorbar. Although any work along those lines would essentially be a reimplementation of `marker_z`. Again it comes down to the options that I listed above.

Just to let you know how things got to be like this. In the past the nodes on a graph used to be Plots.jl markers, so they had all of the properties of Plots.jl markers. Unfortunately, I couldn't work out how to find the precise extent of a marker from inside the `graphplot` recipe. I need to be able to find the perimeter of a marker in order to know where the arrow of a directed edge should stop. Now you can see how we got ourselves into this pickle, I think that we should have a serious discussion of how to get out of it.

**Comment by JackDevine** [comment]
I am going for a walk now, but if you give me an idea of what you are trying to do, then I can try to hack together a solution that doesn't require any changes to GraphRecipes if you like.

**Comment by Datseris** [comment]
I have re-thought Agents.jl plotting, and now it exclusively uses `nodecolor`. The user is supposed to give a function that outputs colors, any valid color. So I won't be using `marker_z`, at least not for Agents.jl.

Notice that the colorbar issue still remains: I would like to know, at least in principle, how can one create a colorbar next to the graph plot. It can't be automatic anymore, as we give colors directly to the `nodecolor`, but of course having a _custom made_ colorbar next to the graph plot is **absolutely crucial**. Without it, I simply can't use the results of these plots in any paper (as it is unacceptable in my eyes to have a scientific paper where something so important, mapping colors to values, is absent).

**Comment by Datseris** [comment]
Reading your reply on how this came to be, I am not sure I would have agreed with it. For being able to know exactly when an arrow should end, I think a lot of very important thinks were sacrificed... 

E.g.: At the moment, not being able to have a stroke around the nodes makes them very hard to use in a figure for a paper: simply put, if I use e.g. the inferno, virids, plasma, binary colormaps, the lighter colors are almost entirely invisible, as they are surrounded by white. A thin outline would immediately fix this.

**Comment by JackDevine** [comment]
> was it really looking that bad by only having an approximate estimate of where the edge arrows should stop? Do you have any examples saved somewhere?

It was pretty bad in my opinion, because any approximation/heuristic that I tried to use had accuracy that varied with the plot size, aspect ratio and even the distance between nodes. There are some examples in #55, but I don't think that they truly show how bad the situation was.

Here is a list of things that we need to get right to reach parity with Plots markers:


markeralpha | ma, malpha, markeralphas, markeropacity, mopacity, mα | `nothing` | Number in [0,1] | The alpha/opacity override for the marker interior.  `nothing` (the default) means it will take the alpha value of markercolor.
-- | -- | -- | -- | --
markercolor | markercolors, markercolour, mc, mcolor, mcolour | `match` | Color Type | Color of the interior of the marker or shape. `:match` will take the value from `:seriescolor`.
markershape | markershapes, shape | `none` | Symbol, Shape, or AbstractVector | Choose  from Symbol[:none, :auto, :circle, :rect, :star5, :diamond, :hexagon,  :cross, :xcross, :utriangle, :dtriangle, :rtriangle, :ltriangle,  :pentagon, :heptagon, :octagon, :star4, :star6, :star7, :star8, :vline,  :hline, :+, :x].
markersize | markersizes, ms, msize | `4` | Number or AbstractVector | Size (radius pixels) of the markers.
markerstrokealpha | markerstrokealphas, markerstrokeopacity, msa, msalpha, msopacity, msα | `nothing` | Number in [0,1] | The  alpha/opacity override for the marker stroke (border).  `nothing` (the  default) means it will take the alpha value of markerstrokecolor.
markerstrokecolor | markerstrokecolors, markerstrokecolour, msc, mscolor, mscolour | `match` | Color Type | Color of the marker stroke (border).  `:match` will take the value from `:foreground_color_subplot`.
markerstrokestyle | markerstrokestyles | `solid` | Symbol | Style of the marker stroke (border).  Choose from Symbol[:auto, :solid, :dash, :dot, :dashdot, :dashdotdot]
markerstrokewidth | markerstrokewidths, msw, mswidth | `1` | Number | Width of the marker stroke (border. in pixels)

Right now it seems that nobody knows how we would go about doing solution 2 from above, so that leaves us with the possibility of copy/pasting a whole bunch of code from Plots to get all of the marker properties working in GraphRecipes.

With regards to colorbars, I have come up with the following:
```julia
using GraphRecipes
using Plots
using LightGraphs

function color_index(x,nodeproperty_data)
    data_range = range(minimum(nodeproperty_data),stop=maximum(nodeproperty_data),length=length(nodeproperty_data))
    findmin(abs.(x.-data_range))[2]
end
N = 8
c1 = colorant"red"
c2 = colorant"green"
g = barabasi_albert(N, 1; seed=42)
weights = [length(neighbors(g,i)) for i in 1:nv(g)]
nodeproperty_data = randn(N)
nodecolor_range = range(c1,stop=c2,length=N)

p = graphplot(g,curves=false,node_weights=weights,linecolor="black",
              names=round.(nodeproperty_data,digits=2),
              nodeshape=:circle,
              nodecolor=[nodecolor_range[color_index(nodeproperty_data[i],nodeproperty_data)] for i in 1:N],
              marker_z=nodeproperty_data,colorbar=:right,color=cgrad([c1,c2]))
```
![colorbar](https://user-images.githubusercontent.com/8610352/76695460-8cdb9980-66e4-11ea-8214-204345a2d7ae.png)

Note that I have put the `nodeproperty_data` into the node names, so you can verify that the colors are being assigned correctly.

This is not a fantastic solution because it is just a (not very good) reimplementation of the already exsisting `marker_z` functionality, but it does demonstrate that we aren't too far from a proper solution. It also gives you a temporary solution while we implement the proper solution.

One thing that I am confused about is that you use the nodesize to indicate the number of neighbours, while you are using the nodecolor to indicate some other thing. I have decided to use the name `nodeproperty_data`, because I don't know what this second thing is. Is it possible that you are slightly overloading the nodes with too much visual data?

**Comment by mkborregaard** [comment]
@JackDevine I'm getting the feeling that you've reimplemented way too much here, adding aliases etc. The standard way is to just add some keywords to the recipes, and then use the Plots pipeline. 
The clear design principle for Plots' functionality is that you should be able to use the same building blocks for every type of plots. That's the key central theme. So that means that linecolor should affect the colors of edges, all marker attributes should affect nodes etc. It's fine to add something else for graph people who don't know about Plots but the core should be the Plots framework.

So I see two possibilities - revert to using markers, or to forward the marker attributes to the attributes you draw at vertices. I don't think that's so difficult though, and if it requires copying code from Plots we're doing something wrong. I assume that each node is just a shape object, and so you could just forward `marker_z` to `fill_z` in the recipe, `markerstrokecolor` to `linecolor` for that relevant series etc. That's quite a commonly used trick.

There are two other issues with using `shape`s though:
1. The aspect ratio = 1 forces the whole graph to take a certain shape, which means that you can't intuitively change the graph layout by changing the shape of the plotting window. - you actually can't change the shape/compression of the graph in each dimension at all, because doing that will affect the markers.

2. When each node has it's own series, it's going to get a copy of the PlotAttributes dict. If you have big graph, you may suddenly end up with 10.000 copies. If the edges work the same way, you've last the ability to visualize graphs of any side.

Maybe instead of doing a full revert, a keyword could switch the behaviours maybe? But if it's just to ensure that arrows end up the right place... I don't know.

**Comment by JackDevine** [comment]
> adding aliases etc..

The aliases that I added are mostly for attributes that are only in GraphRecipes.

> So that means that linecolor should affect the colors of edges, all marker attributes should affect nodes etc.

linecolor does affect edges, the problem here is entirely to do with markers.

> I assume that each node is just a shape object

No, but that would be quite a good idea. I seem to remember finding that difficult without adding Plots as a dependency, since the `Shape` type is not defined in RecipesBase.

> The aspect ratio = 1 forces the whole graph to take a certain shape, which means that you can't intuitively change the graph layout by changing the shape of the plotting window. - you actually can't change the shape/compression of the graph in each dimension at all, because doing that will affect the markers.

Yes, when we solve the this issue we will no longer be restricted to `aspect_ratio=1`, which is a huge bonus in my mind. Although, I wonder if some of the things that you have in mind could actually be achieved with `aspect_ratio=1` and some slightly improved scaling with regards to node placement. For example, if we could make the `layers_scalar` argument for the `:buchheim` method work, then the trees mentioned in #105 would see a big improvement.

With regards to performance, I will admit that there are some things inside `graphplot` that are very suboptimal, however, consider this:
```julia
using LightGraphs
using Plots
using GraphRecipes
g = wheel_graph(1000)

@time graphplot(g,method=:stress) |> display
@time graphplot(g,method=:spring) |> display
```
395.738767 seconds (22.98 G allocations: 450.301 GiB, 10.63% gc time)
  5.070029 seconds (48.64 M allocations: 1.046 GiB, 2.15% gc time)


Which seems like a bug in the stress method. Although assuming that it is not a bug, any performance gains that you might get from refactoring how edges/markers are handled would be swamped by changing `:stress -> :spring`. Right now, `:stress` is our default method, so if we are serious about performance, then it seems that there are lower hanging fruit.

> revert to using markers

I am strongly opposed to a revert, because I feel that it would be an unnecessary step backwards. Although if people want to add that functionality via a keyword argument as you suggest, then I will be fine with that.

For some people, having arrows land in the right place is a cute little feature that doesn't really add to their experience, but for others it could be a make/break feature. Given that Julians are greedy, I don't see why a compromise in this space is even on the table.

**Comment by mkborregaard** [comment]
I'll follow up on the discussion later - but in terms of `shape` you can just add a vector of vertices and set `seriestype = :shape`, then you will not have the Plots dep.
Check the recipes in GeoInterface.jl

**Comment by Datseris** [comment]
@JackDevine I thought it was "impossible" to have colorbars with GraphPlots yet the image you just created is _exactly_ what I am looking for!!!

**Comment by JackDevine** [comment]
I thought that it was not possible without making changes to `graphplot`, but I managed to abuse the inputs until they gave the desired outputs, lol. Notice that there is actually no guaruntee that the colorbar that I passed is the same as the nodecolors, which is why I added the labels as well. I think that what we really want is to be able to pass a marker_z and have `graphplot` automatically give you a colorbar as you originally suggested.

> in terms of shape you can just add a vector of vertices and set seriestype = :shape

Cool, I will look into that when I get time. Perhaps that will be the best way forward.

**Comment by JackDevine** [comment]
Hi all,

Sorry about the delay, I have been quite busy lately. I thought that I would give an update on where I am at with this issue.

@mkborregaard was absolutely right that the nodes were implemented through the shape series type. I somehow convinced myself that I did something different. Sorry about the confusion/drama around that issue.

Although I used the shape series type, I used a new series for each node. In order to get `marker_z` to work, I had to refactor how nodes are handled which took a fair bit of work. On my local copy of GraphRecipes I can do the following:
```julia
N = 8
g = barabasi_albert(N, 1; seed = 42)
weights = [length(neighbors(g, i)) for i in 1:nv(g)]
p = graphplot(g, curvature_scalar=0,
              node_weights=weights, nodesize=0.3,
              linecolor="black", linewidth=2,
              nodeshape=:circle,
              marker_z=rand(N), markercolor=:viridis,
              markerstrokewidth=4,
              markerstrokestyle=:dot,
              markerstrokealpha=0.5,
              markerstrokecolor=:red,
              colorbar=true,
)
```
![marker_graph](https://user-images.githubusercontent.com/8610352/78004856-36828200-7397-11ea-91a4-50a18844570a.png)

I need to do a fair bit of tidying up before I can make a PR, so I would say that a PR fixing this issue will probably not happen for a couple more days. Maybe I will have to wait until the weekend to get a good chunk of time, but we will see.

Thanks for being patient everyone and remember to stay safe.

**Comment by Datseris** [comment]
A small clarification: what happens if both `nodecolor` and `marker_z` are given?

**Comment by JackDevine** [comment]
My plan is to make `nodecolor` and `markercolor` the same thing. So if both `nodecolor` and `marker_z` are given, then the nodecolor is interpreted as a colormap as in the example above with `markershape=:viridis`. On the other hand, `nodecolor` by itself will just be a color, same as before. You should still be able to pass in a vector of colors and have all of the nodecolors be individually specified as before.

It is a little weird that `(node|marker)color` will behave differently depending on the existence of `(node|marker)_z`. But I think that it will be quite easy to get used to.

**Comment by Datseris** [comment]
Alright, thanks.

At the moment we use a method that takes in a function, and that function outputs a _color_ (not a number) for each node. Will this still work? We used to just give this vector to `nodecolor`.

**Comment by JackDevine** [comment]
If you use pass a vector, then that will work. Like in my example above, or this example:
```julia
g = wheel_graph(10)
graphplot(g,curvature_scalar=0,markercolor=rand([:red,:blue,:green],10))
```
![rand_wheel](https://user-images.githubusercontent.com/8610352/78100210-9f720480-7440-11ea-85bf-7668ebd8ebd9.png)

I don't plan to break that functionality with the upcoming fix to this issue

**Comment by JackDevine** [comment]
@Datseris 

Just so you know, the following should work on the latest tagged release:
```julia
using LightGraphs, Plots
using GraphRecipes
using Random

N = 8
g = barabasi_albert(N, 1; seed = 42)
weights = [length(neighbors(g, i)) for i in 1:nv(g)]
nodecolor_range = range(colorant"yellow", stop=colorant"red", length=N)

node_phase = LinRange(0,1,N)
anim = @animate for ϕ in LinRange(0,2π,50)
    Random.seed!(42)
    graphplot(g, curves=false, node_weights = weights,
              linecolor = "black",
              nodeshape = :circle,
              node_z=node_phase.+sin(ϕ),
              method=:spring,
              clims=(-1,2),
              colorbar=:right,
              nodecolor=:RdBu
              )
end
```

![oscillating_nodes](https://user-images.githubusercontent.com/8610352/80898780-b10a3d00-8d5b-11ea-8bab-30d88a1f1aa8.gif)
