### ISSUE TITLE
markerstrokecolor and markerstrokewidth keywords don't have any effect.

### ISSUE THREAD

**Issue by Datseris** [JuliaPlots/GraphRecipes.jl#109]
(self explanatory issue)

```
using GraphRecipes, Plots, LightGraphs
g = barabasi_albert(8, 1; seed = 42)
weights = [length(neighbors(g, i)) for i in 1:nv(g)]
p = graphplot(g, node_weights = weights, nodeshape = :circle, markerstrokecolor = "black", markerstrokewidth=1.5

**Comment by JackDevine** [comment]
Thanks for pointing this out, this wold be a good thing in terms of reaching parity with Plots markers.

Right now, in the canonical GraphRecipes language guide (a bunch of opinions that are in my mind and haven't been communicated publicy), we prefer to use the term "node" over "marker". Perhaps some bikeshedding over using marker/node would be quite valuable.

I prefer the use of node, since anyone plotting a graph should know what a node is. Also, (as you have noticed) there is no guarantee that Plots markers will behave the same as GraphRecipes nodes. I can see why people would prefer maker, since it makes it easier for people who already know Plots to start using GraphRecipes.

Let the bikeshedding begin!

**Comment by Datseris** [comment]
Does your comment mean that there exist `nodestrokecolor` and `nodestrokewidth`? I don't care how they are called in all honesty, as long as they exist and I can use them...

**Comment by JackDevine** [comment]
No, they don't exsist (yet). I wrote down some explanation of the problem in #108 and I have outlined the possible solutions there. Maybe we should shift future discussion to there?
