### ISSUE TITLE
line_z not working as expected & self loops layout obscures plot

### ISSUE THREAD

**Issue by tbenst** [JuliaPlots/GraphRecipes.jl#117]
Hello, thanks for the work on this! I'm fairly new to the JuliaPlots family, so apologies if I'm missing something obvious. I'm trying to plot a graph where the linewidth and color vary per edge.

The example below has two main issues. (1) I want each edge to be a single color and (2) I'd prefer the self loop to not obscure the other edges.

Any tips, or is this a bug or two? Thanks!

![linez](https://user-images.githubusercontent.com/863327/79792798-5fe25e00-8304-11ea-8ea3-ce266a2ded77.png)

```julia
# node 1 is excititory, 2 is inhibitory
graph = SimpleDiGraph(2)
add_edge!(graph, 1,1)
add_edge!(graph, 1,2)
add_edge!(graph, 2,1)
add_edge!(graph, 2,2)

metagraph = MetaGraph(graph)

set_prop!(metagraph, Edge(1,1), :weight, 8.)
set_prop!(metagraph, Edge(1,2), :weight, 1.)
set_prop!(metagraph, Edge(2,1), :weight, 2.)
set_prop!(metagraph, Edge(2,2), :weight, 4.)

set_prop!(metagraph, 1, :name, "E")
set_prop!(metagraph, 2, :name, "I")

graphplot(graph, nodesize=0.4, nodeshape=:circle,
    edge_width=(s,d,w) -> get_prop(metagraph, Edge(s,d), :weight),
    line_z=rand(4),
    names=[get_prop(metagraph,n,:name) for n in 1:size(metagraph)[1]],
    colorbar=true)
```

Related: https://github.com/JuliaPlots/GraphRecipes.jl/issues/39, https://github.com/JuliaPlots/GraphRecipes.jl/issues/1080

Edit: Just noticed a third issue: the linewidth of 1 & 2 appear identical when 2 should be double the width of 1

**Comment by JackDevine** [comment]
Thanks for raising this issue.

It seems that you have uncovered a gold mine of bugs. This is quite an interesting bug. Maybe when we work on #102 we should add a gallery of interesting bugs and their github commit uuid's.

The self-edges pointing in the wrong direction is a little annoying, because when plotting self-edges the first thing that we do is find the emptiest angle a plot all of the self-edges in that direction, try
```julia
using Plots, GraphRecipes, LightGraphs

g = wheel_graph(5)
for i in 1:5
    add_edge!(g,i,i)
end

graphplot(g)
```
to see what I mean. It seems that your graph has bamboozled the `unoccupied_angle` function.

With the other problems, you should see some improvement if you set `curves=false`.

I will definitely add this issue to my todo list. In fact, resolving this issue should block tagging a new release. I might be able to get some time to tackle it properly on the weekend. Are you in any big rush to have this fixed?

**Comment by tbenst** [comment]
@JackDevine thanks for your very kind response! This plot may be relevant for a publication I'm working on, but that won't be submitted for a few weeks yet, so definitely have some time. 

`curves=false` seems to collapse the inter-node edge to a single bidirectional one, while the self-loops are unchanged (I've seen this failure mode on the `I` self-loop with same code above)

![linez](https://user-images.githubusercontent.com/863327/80015230-46691f80-8486-11ea-84ba-41c63f0577a0.png)

**Comment by JackDevine** [comment]
Yes, `curves=false` only gives a modest improvement, I will see what I can do. If you do end up publishing, then let me know. We are putting together a gallery of use cases and I think that figures that go into publications should make sense in the gallery.

**Comment by JackDevine** [comment]
**UPDATE**

On my computer, I get the following:
```julia
graph = SimpleDiGraph(2)
add_edge!(graph, 1,1)
add_edge!(graph, 1,2)
add_edge!(graph, 2,1)
add_edge!(graph, 2,2)

metagraph = MetaGraph(graph)

set_prop!(metagraph, Edge(1,1), :weight, 8.)
set_prop!(metagraph, Edge(1,2), :weight, 1.)
set_prop!(metagraph, Edge(2,1), :weight, 2.)
set_prop!(metagraph, Edge(2,2), :weight, 4.)

set_prop!(metagraph, 1, :name, "E")
set_prop!(metagraph, 2, :name, "I")

graphplot(graph, nodesize=0.15, nodeshape=:circle,
    fontsize=12,
    # edge_width=(s,d,w) -> get_prop(metagraph, Edge(s,d), :weight),
    edge_width=[get_prop(metagraph, Edge(s,d), :weight) for s in 1:2, d in 1:2][:]',
    line_z=rand(1,4),
    color=:reds,
    names=[get_prop(metagraph,n,:name) for n in 1:size(metagraph)[1]],
    colorbar=true,
    selfedgesize=0.8,
    curvature_scalar=0.15,
    nodestrokewidth=1.5,
    axis_buffer=1.0,
    nodecolor=:orange
    )
```
![neurons](https://user-images.githubusercontent.com/8610352/80299480-c2e26200-87e8-11ea-8d62-6d6d6875947c.png)

Note that I didn't pass `edgewidth` a function, I passed it an array. Also note that I passed `line_z` a row vector. If you pass it a column vector, then `graphplot` gets very confused. Basically, my local version that makes this example work needs a little tidying before it can be merged. I can make a WIP pull request if you really want to see what I have so far.

One thing that I have noticed is that you passed `edgewidth` the weights for your edges and you passed `line_z` another vector. Presumably the widths of the edges represent how connected neurons are in your model and the colors of the edges are meant to represent some other property of the connections. I noticed a similar thing in #108, where the user wanted the node sizes to mean one thing and the node colors to mean something else. Personally, I like the colors and sizes to complement each other, so I think that in both cases the graph could be displayed more clearly using one of two methods:
1.  Have two subplots where the sub titles tell you what the colorbar and edge/nodesizes indicate. In both subplots, the sizes and colors of edges/nodes display the same property
2. In an interactive setting (doesn't apply to publications) make it so that hovering over an edge or a node displays metadata in an associated metagraph

Having said all that, I don't think that the API should prohibit cases where the colors and the sizes represent different data. In fact, I think that the API should make it easy to assign metagraph properties to edge/node properties. Here is my thinking for the API:

Make keyword arguments `(node|edge)_z` which can be set separately. The `edge_z` argument will accept either a function of the form `(s,d,w) -> property`, a graph/matrix containing the edge widths or a metagraph and an associated property of the metagraph. Likewise, the `edgewidth` keyword argument should accept more than just a function. In a different PR, we could add a method to `graphplot` which takes a graph and a metagraph. As long as `graphplot` is able to find the right metadata in the metagraph, then it will use that info to tweak the layout. This kind of API would work really well in an interactive setting.

Using this API, you could have a plot where the sizes and colors of the nodes mean two different things and likewise for the edge widths and colors. Maybe I am a little simple minded, but I would find such a plot to be rather confusing.

Again, I don't think that the API should prohibit these rather complicated use cases. I could be proven wrong and it turns out that exploiting the colors and the sizes of edges/nodes is a very efficient way to display/consume information.

In any case, I plan to make a PR some time tomorrow. If anyone wants to discuss the API that I have proposed, then feel free to ping me in this issue.

**Comment by tbenst** [comment]
@JackDevine wow, that was quick and the plot is beautiful, great job and thank you!

> Presumably the widths of the edges represent how connected neurons are in your model and the colors of the edges are meant to represent some other property of the connections. 

In this case, I plan on the color representing the "current" traveling over that edge. So indeed it's related to the connnection strength/edge width, but current may vary over time whereas in my model the connectivity does not.

>  In a different PR, we could add a method to graphplot which takes a graph and a metagraph.

Love this idea.
