### ISSUE TITLE
No arrow appears when drawing `SimpleDiGraph`

### ISSUE THREAD

**Issue by keorn** [JuliaPlots/GraphRecipes.jl#126]
```
using GraphRecipes, Plots, LightGraphs
g = SimpleDiGraph([Edge(1, 2)])
graphplot(g)
```

![image](https://user-images.githubusercontent.com/7750981/82138430-ac945880-9820-11ea-8b40-dad527a4dbe8.png)

**Comment by dietercastel** [comment]
From [the docs](http://docs.juliaplots.org/latest/graphrecipes/examples/#Directed-Graphs-1) it seems that indeed that should be expected.

You can remedy it right now by explicitly specifying you want arrows
```julia
using GraphRecipes, Plots, LightGraphs
g = SimpleDiGraph([Edge(1, 2)])
graphplot(g,arrow=true)
# or e.g. 
# graphplot(g,arrow=:closed)
```

**Comment by dietercastel** [comment]
I dove into this one and got to the root of it which is [this line](https://github.com/JuliaPlots/GraphRecipes.jl/blob/7c5f643826266413fdea2c14da4fd3fc56fee39e/src/graphs.jl#L362)
```julia
!in(method, (:tree, :buchheim)) && !(get(plotattributes, :arrow, false) == false)
```
should probably be fixed to 
```julia
!in(method, (:tree, :buchheim)) && !(get(plotattributes, :arrow, true) == false)
```
since treating arrows as default on (true as third argument in for directed graphs seems reasonable (and implied by the docs, so I assume desired).

I think the "directed" test file also accidentally got overwritten with a version without arrows which is probably why it slipped under the radar. Previously it was like this ![](https://github.com/JuliaPlots/GraphRecipes.jl/raw/1eaa2b6a3488887a876160d899fd4c535ed89413/assets/directed.png) 
and now it's this one
![](https://github.com/JuliaPlots/GraphRecipes.jl/raw/master/assets/directed.png)

I'll create a PR to fix it (and the test) soon.
