### ISSUE TITLE
Minimal example gives nonsense.

### ISSUE THREAD

**Issue by kzapfe** [JuliaPlots/GraphRecipes.jl#56]
I create the following adjacency matrix:

A
5×5 Array{Float64,2}:
 0.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0
 1.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0  1.0
 0.0  0.0  0.0  1.0  0.0

which as you can tell, is sparsingly conected graph. But if I call 
graphplot(A)
it just generates the complete K5 Graph, that is, every node is connected to every other node. 
I have tried with more nodes, with 'linewidth' keyword, imitating the example, etc. Its all the same, it allways gives a full graph no matter the input.

**Comment by ericphanson** [comment]
Strangely, even `graphplot(zeros(5,5), method=:chorddiagram)` gives a complete graph (although without `method=:chorddiagram`, it shows nothing, which seems reasonable).

**Comment by JackDevine** [comment]
Very strange indeed. On master, I get the following behaviour:
```julia
using Plots, GraphRecipes, LightGraphs

A = [0.0 0.0 1.0 0.0 0.0;
     0.0 1.0 0.0 1.0 0.0;
     1.0 0.0 1.0 0.0 0.0;
     0.0 1.0 0.0 0.0 1.0;
     0.0 0.0 0.0 1.0 0.0]

p1 = graphplot(A,names=1:5)
p2 = graphplot(DiGraph(A),names=1:5)
plot(p1,p2)
```
![incorrect_graph](https://user-images.githubusercontent.com/8610352/71762992-8fc74a80-2f3b-11ea-8d93-bfc7d5c2ee0c.png)

So it gets it right if you pass a `LightGraphs.Graph` rather than an array.

> Strangely, even `graphplot(zeros(5,5), method=:chorddiagram)` gives a complete graph

Again, passing a `LightGraphs.Graph` makes a little more sense. `graphplot(Graph(zeros(5,5)), method=:chorddiagram)` is an error.

Maybe the answer is to always convert to a `LightGraphs.Graph`. LightGraphs is already a dependency, so I don't think it would be a big problem. I will have a deeper look and decide what is the best option.
